TravelAgency.Web/Areas/Admin/Controllers/HomeController.cs
namespace TravelAgency.Web.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Services.Data.Interfaces;
    

    public class HomeController : BaseAdminController
    {
        
        
        public IActionResult Index()
        {
           
            return View();
        }
    }
}

TravelAgency.Web/Areas/Admin/Controllers/HotelController.cs
namespace TravelAgency.Web.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using ViewModels;

    public class HotelController : BaseAdminController
    {
        //public IActionResult AllReservation()
        //{
        //    AllHotelViewModel viewModel = new AllHotelViewModel()
        //    {

        //    };
        //}
    }
}

TravelAgency.Web/Areas/Admin/Controllers/ReservationController.cs
namespace TravelAgency.Web.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Caching.Memory;
    using Services.Data.Interfaces;
    using Web.ViewModels.Reservation;

    using static Common.GeneralApplicationConstants;

    public class ReservationController : BaseAdminController
    {
        private readonly IReservationService reservationService;
        private readonly IMemoryCache memoryCache;

        public ReservationController(IReservationService reservationService, IMemoryCache memoryCache)
        {
            this.reservationService = reservationService;
            this.memoryCache = memoryCache;
        }
        
        
        [Route("Reservation/All")]
        [ResponseCache(Duration = 120, Location = ResponseCacheLocation.Client, NoStore = false)]
        public async Task<IActionResult> All()
        {
            var allReservation = await this.reservationService.AllAsync();

            //IEnumerable<ReservationViewModel> allReservation =
            //    this.memoryCache.Get<IEnumerable<ReservationViewModel>>(ReservationsCacheKey);
            //if (allReservation == null)
            //{
            //    allReservation = await this.reservationService.AllAsync();

            //    MemoryCacheEntryOptions cacheOptions = new MemoryCacheEntryOptions()
            //        .SetAbsoluteExpiration(TimeSpan.FromMinutes(ReservationCacheDurationMinutes));

            //    this.memoryCache.Set(UserCacheKey, allReservation, cacheOptions);
            //}
            
            return this.View(allReservation);
        }
    }
}

TravelAgency.Web/Controllers/HomeController.cs
namespace TravelAgency.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    using TravelAgency.Services.Data.Interfaces;
    using ViewModels.Home;

    using static Common.GeneralApplicationConstants;
    

    public class HomeController : Controller
    {
        private readonly IHotelService _hotelService;

        public HomeController(IHotelService hotelService)
        {
            this._hotelService = hotelService;
        }

        public async Task<IActionResult> Index()
        {
            if (this.User.IsInRole(AdminRoleName))
            {
                return this.RedirectToAction("Index", "Home", new {Area = AdminAreaName});
            }


            IEnumerable<IndexViewModel> viewModel = await this._hotelService.LastThreeAddedHotelAsync();

            return View(viewModel);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(int statusCode)
        {
            if (statusCode == 404 || statusCode == 400)
            {
                return this.View("Error404");
            }

            if (statusCode == 401)
            {
                return this.View("Error401");
            }

            return this.View();
        }
    }
}

TravelAgency.Web/Controllers/UserController.cs
namespace TravelAgency.Web.Controllers;

using Data.Models;
using Microsoft.AspNetCore.Mvc;

using TravelAgency.Services.Data.Interfaces;
using Infrastructure.Extensions;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Caching.Memory;
using ViewModels.User;

using static Common.NotificationMessagesConstants;
using static Common.GeneralApplicationConstants;

[Authorize]
public class UserController : Controller
{
    private readonly SignInManager<ApplicationUser> signInManager;
    private readonly UserManager<ApplicationUser> userManager;
    private readonly IUserService userService;
    private readonly IMemoryCache memoryCache;

    public UserController(IUserService userService, SignInManager<ApplicationUser> signInManager, 
        UserManager<ApplicationUser> userManager, IMemoryCache memoryCache)
    {
        this.signInManager = signInManager;
        this.userManager = userManager;
        this.userService = userService;
        this.memoryCache = memoryCache;
    }


    [AllowAnonymous]
    [HttpGet]
    public IActionResult Register()
    {
        return View();
    }

    [AllowAnonymous]
    [HttpPost]
    public async Task<IActionResult> Register(RegisterFormModel model)
    {
        if (!ModelState.IsValid)
        {
            return this.View(model);
        }

        ApplicationUser user = new ApplicationUser()
        {
            FirstName = model.FirstName,
            LastName = model.LastName,
            PhoneNumber = model.PhoneNumber,
        };

        await this.userManager.SetEmailAsync(user, model.Email);
        await this.userManager.SetUserNameAsync(user, model.Email);

        IdentityResult result =
            await this.userManager.CreateAsync(user, model.Password);

        if (!result.Succeeded)
        {
            foreach (IdentityError error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }

        await this.signInManager.SignInAsync(user, false);
        this.memoryCache.Remove(UserCacheKey);

        return this.RedirectToAction("Index", "Home");
    }
    
    [AllowAnonymous]
    [HttpGet]
    public async Task<IActionResult> Login(string? returnUrl = null)
    {
        await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);
        
        LoginFormModel model = new LoginFormModel()
        {
            ReturnUrl = returnUrl
        };
        
        return this.View();
    }

    [AllowAnonymous]
    [HttpPost]
    public async Task<IActionResult> Login(LoginFormModel model)
    {
        if (!ModelState.IsValid)
        {
            return this.View(model);
        }

        var result =
            await this.signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, false);

        if (!result.Succeeded)
        {
            this.TempData[ErrorMessage] = 
                "There was an error while logging you in! Please try again latter ot contact an administrator!";
            
            return View(model);
        }

        return this.Redirect(model.ReturnUrl ?? "/Home/Index");
    }


    
    [HttpGet]
    public async Task<IActionResult> Order()
    {
        List<UserAllReservationViewModel> myOredr = new List<UserAllReservationViewModel>();

        string userId = this.User.GetId()!;


        myOredr.AddRange(await this.userService.AllUserReservationAsync(userId!));


        return this.View(myOredr);
    }

    [HttpGet]
    public async Task<IActionResult> MyWish()
    {
        List<UserAllReservationViewModel> myOredr = new List<UserAllReservationViewModel>();

        string userId = this.User.GetId()!;


        myOredr.AddRange(await this.userService.AllUserReservationAsync(userId!));


        return this.View(myOredr);
    }
}

TravelAgency.Web/Areas/Admin/Views/Home/Index.cshtml
@using TravelAgency.Services.Data
@using Microsoft.AspNetCore.Identity
@using TravelAgency.Data.Models
@using TravelAgency.Services.Data.Interfaces
@inject UserManager<ApplicationUser> UserManager
@inject IUserService UserService
@{
    ViewData["Title"] = "Home Page";
    string userFullName = await UserService.GetFullNameByEmailAsync(this.User.Identity?.Name!);
}

<div class="mt-4 p-5 bg-light text-center">
    <h2 class="display-4">Здравей, @userFullName</h2>
    <p class="lead mb-1 mt-3">
        <div class="container mt-5">
            <h2>Добре дошли във вашето администраторско табло за управление на хотелската платформа!</h2>
            <p>
                Тук можете да наблюдавате и контролирате списъците си с хотели, осигурявайки безпроблемно изживяване за вашите потребители. Можете да изпълнявате набор от основни задачи:
            </p>

            <h3>Управление на хотелите:</h3>
            <ul>
                <strong>Описание към всеки хотел</strong>, включитено име, местоположение, категория, вид на изхранването и др.
                <strong>Да създавате хотели</strong>, да добавяте снимки и описание.
                <strong>Да редактиарте информацията за съществуващи хотели</strong>, попържайки винаги актуална информация.
                <strong>Да изтривате хотели</strong> когато това е необходимо.
                <strong>Мониторинг на резервациите</strong> за да менажирате ефективно.
            </ul>

            <h3>Управление на потребители:</h3>
            <ul>
                <strong>Можете да виждате кой е онлайн</strong> от регистрираните в пратвормата.
                <strong>Осигурете безпроблемно потребителско изживяване.</strong>
            </ul>

            <h3>Мониторинг на резервациите:</h3>
            <ul>
                <strong>Вижте всички резервации</strong> направени в системата.
                <strong>Управлявайте резервациите</strong>, за да гарантирате, че няма да възникнат конфликти.
                <strong>Наблюдавайте приходите</strong>, за да оптимизирате работата си.
            </ul>
            
            <p>
                Вашата роля на администратор е от решаващо значение за поддържане на качествена услуга!
            </p>

            <p>
                Приятно управление!
            </p>
        </div>


    </p>
    
    <hr class="my-4">
    <a asp-area="" asp-controller="Hotel" asp-action="All" class="btn btn-primary btn-lg">All Hotels</a>
    <span>  |   </span>
    <a asp-area="" asp-controller="Hotel" asp-action="Add" class="btn btn-primary btn-lg">Add Hotel</a>
    <span>  |   </span>
    <a asp-area="Admin" asp-controller="Reservation" asp-action="All" class="btn btn-primary btn-lg">All Reservations</a>
    <span>  |   </span>
    <a asp-area="Admin" asp-controller="User" asp-action="AllUsers" class="btn btn-primary btn-lg">All Users</a>
</div>